### PR TITLE
added an option to include columns with a not null contraint

### PR DESCRIPTION
**Pull request by dwa012**

### CODE REVIEW

**Comment by rubiety** [comment]
From an API point of view, I'm not sure I like using the key `any` here - it's too vague and doesn't literally mean what it implies ("any column", since we're still restricting by type and with `content_columns`, per discussion on #27). Maybe `:nullables_only => false` or something more descriptive? Not sure I have a good key in mind myself.

**Comment by dwa012** [comment]
@rubiety I am not the best at naming keys. I had made the change for a need that I had.
I think ``:nullables_only => false`` sounds good to me.

**Comment by jibiel** [comment]
Yep, this is a tricky one. Can't think of anything more descriptive myself, so :thumbsup: for `nullables_only: false` / `skip_nullables: false`.

**Comment by dgobaud** [comment]
Looks good just need to make sure it works globally such as

ActiveRecord::Base.nilify_blanks : skip_nullables => flase

**Comment by jibiel** [comment]
```ruby
# config/initializers/nilify_blanks.rb
ActiveRecord::Base.nilify_blanks skip_nullables: false
```
Works for me on `rails 4.2.5`!
I think it always worked, some users just didn't expect it will be skipping `null: false` fields silently.

**Comment by jibiel** [comment]
@rubiety Any updates on that?

**Comment by rubiety** [comment]
Would be happy to accept a pull request implementing the above with appropriate tests, from the original author or otherwise.

**Comment by rubiety** [comment]
I have implemented this myself in commit c5a4af9 to `master` with tests, closing this pull request.

**Pull request closed without merging**
